---
root: true

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2018
  sourceType: module

  project:
  - "./tsconfig.json"

plugins:
  - "@typescript-eslint"
  - prettier
  - jest

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - standard

  - prettier/@typescript-eslint
  - prettier/standard
  - plugin:jest/recommended
  - plugin:jest/style

  # This one should come last
  - plugin:prettier/recommended

rules:
  prettier/prettier: error
  # this prevents method overloading, and tsc will fail for duplicate class members anyway
  "no-dupe-class-members": off
  # explicit any will silently disable a lot of type checking, try to abstain as much as possible!
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/no-unused-vars":        [error, {argsIgnorePattern: "^_"}]
